### ISSUE TITLE
Print error outputs to 'stderr' or add a quiet CLI flag

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-contrib/sphinx-lint#101]
"No problems found." is printed when it's all good, but I'd rather have nothing printed at all. It tried redirecting the output to /dev/null (`sphinx-list some_file > /dev/null`), but this also masks the error outputs — because these outputs are currently not sent to stderr (standard error output).

So, my suggestion is to implement either one: to print error messages to stderr (e.g. `print('This is an error message', file=sys.stderr)`) or to have a -q / --quiet flag added to have nothing print if no problems are found.

For reference: https://github.com/sphinx-contrib/sphinx-lint/blob/5b2e1b86ddccdef24b0749cebc32d990a64e63f5/sphinxlint/cli.py#L194-L202

**Comment by AlexWaygood** [comment]
I think a well-behaved CLI should send error messages to stderr, for sure. I'd happily accept a PR implementing that!
