### ISSUE TITLE
[feature request] Add --quiet option

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-contrib/sphinx-lint#124]
Would be nice to have an option for silencing normal output messages (not errors and warnings) whenever desired. Taking Sphinx as an example, `-q` / `--quiet` would be great options.

**Comment by hugovk** [comment]
Sounds reasonable, please could you give some example current output, and how it might look with `--quiet`?

**Comment by rffontenelle** [comment]
I'm sorry, my intention was to request in sphinx-intl, but I did a letter soup I filed the request in here instead. To be honest, I can't find useful to run sphinx-lint only to get error exit status, so outputting the problematic files seems a great deal.
