### ISSUE TITLE
default-role should not be reported as an issue by default

### ISSUE THREAD

**Issue by matilda-me** [sphinx-contrib/sphinx-lint#14]
My projects and many other are using default role, quoting [the doc](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html):

> The default role (`content`) has no special meaning by default. You are free to use it for anything you like

Maybe this should not be enabled by default?

**Comment by JulienPalard** [comment]
@matilda-me ezio is right, can you please test the latest version of sphinx-lint? Don't hesitate to re-open an issue if needed.
