### ISSUE TITLE
Improve regex to detect chars immediately after inline literals and roles

### ISSUE THREAD

**Issue by ezio-melotti** [sphinx-contrib/sphinx-lint#30]
From https://github.com/sphinx-contrib/sphinx-lint/pull/27#discussion_r867462125: some characters (such as punctuation) are allowed immediately after inline literals and roles, whereas others (alphanumerical) aren't. 

The following regex could be improved to catch only the problematic characters:
https://github.com/sphinx-contrib/sphinx-lint/blob/1c5adaaf5c3c91dcb75355a5e297f4676cd5f3db/sphinxlint.py#L207

Replacing the last `.` with `\w` seems to cause lot of false positives though.

**Comment by JulienPalard** [comment]
I think this is now fixed, not because we enhanced the regex, but because all legitimate constructions are hidden from this detector via the `paragraph = clean_paragraph(paragraph)` call one line before the regex.

Don't hesitate to re-open if you have an example.
