### ISSUE TITLE
Option to sort output

### ISSUE THREAD

**Issue by rtobar** [sphinx-contrib/sphinx-lint#50]
I tried this tool today and it's great, thanks!

I found that having an option to sort the output would be great when inspecting an error report. At the moment I'm guessing the output is scrambled as the multiple subprocesses produce results, and while this gives you fast feedback as the tool runs, it's difficult to parse when running against a set of files (which ones have the most errors?), or even a single file (`file:number` alignment is not consistent).

Just an idea, not a deal brearker.

**Comment by JulienPalard** [comment]
You guess right.

What about something like `--sort-by=filename`, `--sort-by=most-errors`, `--sort-by=error-type`, `--sort-by=filename,error-type` (to sort by filename, and within a single file to sort by error type)?

Which sorting would fit your need the best?

**Comment by hugovk** [comment]
Maybe default to the same order as existing linters like Flake8?

**Comment by JulienPalard** [comment]
Fixed in #51.
