### ISSUE TITLE
v0.6.8 tag missing on main branch

### ISSUE THREAD

**Issue by adamchainz** [sphinx-contrib/sphinx-lint#73]
I installed sphinx-lint with pre-commit this week, and now pre-commit.ci is "upgrading" my projects from `v0.6.8` to `v0.6.7` (example: https://github.com/evansd/whitenoise/pull/515). I think this is because it's grabbing the latest tag on `main`, and the commit tagged `v0.6.8` is missing from `main`: https://github.com/sphinx-contrib/sphinx-lint/commit/32df02058e88cc2fb1092d84fb1124760ce81a27 .

GitHub is even showing a warning for that commit:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

You could get it back onto `main` with a rebase and force push.

**Comment by hugovk** [comment]
I've cherry picked that commit into `main`, rebased, retagged, and republished the release:

* https://github.com/sphinx-contrib/sphinx-lint/releases/tag/v0.6.8

`pre-commit autoupdate` now upgrades instead of downgrading.

Thanks for letting us know!

**Comment by adamchainz** [comment]
Git trickzzzz
