### ISSUE TITLE
AttributeError: Can't get attribute '_check_file' on <module '__main__' (built-in)>

### ISSUE THREAD

**Issue by jaraco** [sphinx-contrib/sphinx-lint#83]
In the [cssutils](/jaraco/cssutils) project, the `sphinxlint` command has started [failing on my macOS Python 3.11.6 environment](https://gist.github.com/jaraco/a4a9ab431099d25d28cbcf6887348ea2).

The execution emits a lot of errors and then hangs until I interrupt it.

The issue isn't currently happening in CI, so I'm suspicious the Python 3.11.6 update may be implicated.

**Comment by jaraco** [comment]
I've started to notice the same issue in other projects ([distutils](/pypa/distutils)).

**Comment by jaraco** [comment]
But yet other projects ([jaraco.functools](/jaraco/jaraco.functools)) are unaffected. Could the difference be how many files are in the docs?

**Comment by jaraco** [comment]
The issue doesn't occur if I invoke `sphinx-lint` (the command runs to completion) instead of `python -m sphinxlint`. The issue also doesn't occur if I remove `docs/distutils` (the bulk of the docs).

**Comment by jaraco** [comment]
The issue emerges between [0.6.7 and 0.6.8](https://github.com/sphinx-contrib/sphinx-lint/compare/v0.6.7...v0.6.8).

**Comment by hugovk** [comment]
I can reproduce with cssutils when running via `python -m sphinxlint docs` (as used in the cssutils tox.ini), but not when running as `sphinx-lint docs`:

```console
❯ sphinx-lint docs
No problems found.
```

0.6.8 is when `sphinxlint/__main__.py` was added with all the `multiprocessing` handling.

**Comment by jaraco** [comment]
The offending commit [appears to be](https://gist.github.com/jaraco/8612c5ed61affc47c88a3028f083cda8) 42f1b98299dc5be6b4e2111d77369793a70028b2.

**Comment by hugovk** [comment]
Looks like it's this: 

* https://stackoverflow.com/a/42383397/724176
* https://github.com/python/cpython/issues/69240

And the fix is to move `_check_file` out of `__main__.py` and import it instead.

Here's a quick demo fix: 

```diff
diff --git a/sphinxlint/__init__.py b/sphinxlint/__init__.py
index 91df074..55d9bdb 100644
--- a/sphinxlint/__init__.py
+++ b/sphinxlint/__init__.py
@@ -6,4 +6,12 @@ from sphinxlint.sphinxlint import check_file, check_text
 
 __version__ = importlib.metadata.version("sphinx_lint")
 
-__all__ = ["check_text", "check_file"]
+__all__ = ["check_text", "check_file", "_check_file"]
+
+
+def _check_file(todo):
+    """Wrapper to call check_file with arguments given by
+    multiprocessing.imap_unordered."""
+    return check_file(*todo)
+
+
diff --git a/sphinxlint/__main__.py b/sphinxlint/__main__.py
index 5a1290b..4835501 100644
--- a/sphinxlint/__main__.py
+++ b/sphinxlint/__main__.py
@@ -5,7 +5,7 @@ import os
 import sys
 from itertools import chain, starmap
 
-from sphinxlint import check_file, __version__
+from sphinxlint import check_file, __version__, _check_file
 from sphinxlint.checkers import all_checkers
 from sphinxlint.sphinxlint import CheckersOptions
 
@@ -166,12 +166,6 @@ def walk(path, ignore_list):
             yield file if file[:2] != "./" else file[2:]
 
 
-def _check_file(todo):
-    """Wrapper to call check_file with arguments given by
-    multiprocessing.imap_unordered."""
-    return check_file(*todo)
-
-
 def sort_errors(results, sorted_by):
     """Flattens and potentially sorts errors based on user prefernces"""
     if not sorted_by:
```

```console
❯ sphinx-lint docs
No problems found.

cssutils on  main [?] via 🐍 v3.12.0
❯ python -m sphinxlint docs
No problems found.
```

**Comment by jaraco** [comment]
I suspect the issue is that when `multiprocessing` is involved, `_check_file` is passed into the pool workers, but when invoked by `runpy`, `__main__` is found at the top level and not in `sphinxlint.__main__`, so fails to be reimported in the worker.

**Comment by jaraco** [comment]
My recommendation would be to move nearly all logic out of `sphinxlint.__main__` into another module (`sphinxlint.cli` maybe, or just `sphinxlint`). Doing so would avoid the temptation to include behavior that may need to be imported.

**Comment by jaraco** [comment]
I've also determined that by setting `--jobs 1`, it bypasses the multiprocessing, matching the behavior observed in CI where the issue doesn't occur.

Let me know if you'd like me to present the PR (especially if you're interested in the `sphinxlint.cli` approach).

**Comment by hugovk** [comment]
I've already started on doing `sphinxlint.cli` :)

**Comment by hugovk** [comment]
Please see PR https://github.com/sphinx-contrib/sphinx-lint/pull/99, thanks for the investigation and suggestions!
